### ISSUE TITLE
Planning - Interview Questions

### ISSUE THREAD

**Issue by lapinell** [nss-day-cohort-24/chatty-pineapple-metal#1]
Interview at least two students

**Comment by lapinell** [comment]
1. How old are you?
1. What is your current occupation outside of NSS?
1. When a new piece of technology (like a new smartphone or gaming console) comes out what do you do? 
    * Buy it immediately
    * Wait until others have tried it and see what they say
    * Wait until the price drops after most people have bought it
    * Don't buy it or wait until I need something new
1.  Income-wise: how many figures do you make?
    * no income 
    * less than $10,000/year
    * between $10,000/year and $50,000/year
    * over $50,000/year
1. What skills did you currently have as it pertains to being a student at NSS? (coding, computer, writing, desiging, etc)
1. As a student at NSS, if NSS were willing to provide you with something you need, what would it be?
1. As a student at NSS, what most frustrates you?
1. As a student at NSS, what do you primarily discuss with your classmates or other students?
1. As a student at NSS, what would you talk about in a public chatroom designed specifically for students at NSS?

**Comment by lapinell** [comment]
@Batkins44 @mulhollen @jeremylukebennett - please look over and add any suggestions or feedback in comments

**Comment by Batkins44** [comment]
Interview Results

How old are you?: 
**20**

What is your current occupation outside of NSS? 
**Unemployed**

When a new piece of technology (like a new smartphone or gaming console) comes out what do you do?
Buy it immediately
**Wait until others have tried it and see what they say ----- This one!**
Wait until the price drops after most people have bought it
Don't buy it or wait until I need something new

Income-wise: how many figures do you make? 
**no income ------------This one**
less than $10,000/year
between $10,000/year and $50,000/year
over $50,000/year

What skills did you currently have as it pertains to being a student at NSS? (coding, computer, writing, desiging, etc) 
**Basic HTML, CSS, and Javascript. Did the jumpstart**

As a student at NSS, if NSS were willing to provide you with something you need, what would it be?

**More consistent internet**

As a student at NSS, what most frustrates you?
**The internet**

As a student at NSS, what do you primarily discuss with your classmates or other students?
**Coding Mainly**

As a student at NSS, what would you talk about in a public chatroom designed specifically for students at NSS?
**Post Gifs and keep up with group projects**
