### ISSUE TITLE
Planning - Create Persona

### ISSUE THREAD

**Issue by lapinell** [nss-day-cohort-24/chatty-pineapple-metal#2]

**Comment by Batkins44** [comment]
**Hypothesized NSS Student** 

1. Demographics:

- Age ~30's
- occupation: PT or no job
- Skills: some PC skills, little bit o code
-Adopter:Early majority
-Income $ or $$ :(

2. Key Behaviors:
-Eager to Learn
-Communicates with other students
-primarily about projects,to vent, about material, ask questions to others

3. Needs and frustrations
-Stuck on a problem or error
-Not understanding the material
-Where are group mates in the project?
-Need to share snippets of code.

**Comment by lapinell** [comment]
# Final Persona Breakdown:

**Demographics:**
- Age: 32
- occupation: no job
- Adopter: Early majority
- Income: no income
- Skills:
* HTML, CSS, JS
* design
* time management
* organized
* teaches
* communicates well

**Key Behaviors:**
-Frustrated
-Eager to Learn
-Communicates with other students about
   * projects and materials
   * advice and support
   * frustrations
   * small talk/stuff outside NSS

**Needs and frustrations**

- a place to find support and advice
- no way to easily catch up
- lack of tutoring
- speed of material
- class management style
- class noise level
- lack of feeling safe asking questions (feeling like they are asking "stupid" questions)
- mac bias
- money
- loan system
- garbage disposal
- lack of ability to effectively communicate with peers

**Goals**
1. Provide me a place to safely communicate my frustrations and find help and support from peers.
