### ISSUE TITLE
Planning: Interview Student 2

### ISSUE THREAD

**Issue by lapinell** [nss-day-cohort-24/chatty-pineapple-metal#21]
1. How old are you?
1. What is your current occupation outside of NSS?
1. When a new piece of technology (like a new smartphone or gaming console) comes out what do you do? 
    * Buy it immediately
    * Wait until others have tried it and see what they say
    * Wait until the price drops after most people have bought it
    * Don't buy it or wait until I need something new
1.  Income-wise: how many figures do you make?
    * no income 
    * less than $10,000/year
    * between $10,000/year and $50,000/year
    * over $50,000/year
1. What skills did you currently have as it pertains to being a student at NSS? (coding, computer, writing, desiging, etc)
1. As a student at NSS, if NSS were willing to provide you with something you need, what would it be?
1. As a student at NSS, what most frustrates you?
1. As a student at NSS, what do you primarily discuss with your classmates or other students?
1. As a student at NSS, what would you talk about in a public chatroom designed specifically for students at NSS?

**Comment by mulhollen** [comment]
How old are you?
- early 30's

What is your current occupation outside of NSS?
- front-end developer

When a new piece of technology (like a new smartphone or gaming console) comes out what do you do?
-Wait until others have tried it and see what they say

Income-wise: how many figures do you make?
no income
- before nss: between $10,000/year and $50,000/year

What skills did you currently have as it pertains to being a student at NSS? (coding, computer, writing, desiging, etc)
-coding, design

As a student at NSS, if NSS were willing to provide you with something you need, what would it be?
-Video recaps/explanations that I can watch over and over again if needed.

As a student at NSS, what most frustrates you?
-Getting lost, and not having great ways to catch up (that firehose keeps going and I can only drink so much at a time)

As a student at NSS, what do you primarily discuss with your classmates or other students?
-What I’m confused about / feel like I missed / venting /comiserating

As a student at NSS, what would you talk about in a public chatroom designed specifically for students at NSS?
-Share memes and gifs
