### ISSUE TITLE
Planning - Challenge Statement

### ISSUE THREAD

**Issue by lapinell** [nss-day-cohort-24/chatty-pineapple-metal#25]
Develop a challenge statement based off of the persona

**Comment by mulhollen** [comment]
How might we provide NSS students with a method to communicate frustrations and confide with each other through the medium of a chat room.

**Comment by Batkins44** [comment]
Ultimate impact:

How might we provide NSS students with a method to communicate frustrations and confide with each other through the medium of a chat room.

Solutions:

Email, Snailmail, Slack, Private Room

Constraints:
Cant share code or projects
Share gifs or emotimages
history saved
