### ISSUE TITLE
Web Part: themes.js

### ISSUE THREAD

**Issue by lapinell** [nss-day-cohort-24/chatty-pineapple-metal#31]
- [x] 1. When the user clicks on the dark theme checkbox, change the background color of your application to a darker shade, and the font color for messages should be light.
- [x] 1. If the user unchecks the box, the background color should change back to a lighter color with darker color text for messages.

**Comment by jeremylukebennett** [comment]
Checking and unchecking the checkbox toggles different functionality (this has been what's taken the bulk of the time to sort out), and now its a matter of applying the appropriate stylings to each state. 

Same functionality is in place with the Large text checkbox, and stylings simply need to be added to each.
